site_name: JRP.best docs
site_description: 'JRP.best docs'
site_author: 'JRP.best'
docs_dir: docs/
repo_name: 'Jrp-best-hosting/docs'
repo_url: 'https://github.com/Jrp-best-hosting/docs'
nav:
    - Home: index.md
    - Deploying: deploying.md
    - Api: api.md
theme:
  name: 'material'
