site_name: Griphitor docs
site_description: 'Griphitor docs'
site_author: 'Griphitor Team'
docs_dir: docs/
repo_name: 'Griphitor/Documentation'
repo_url: 'https://github.com/Griphitor/Documentation'
nav:
    - Home: index.md
    - Pre-Included Libs: libraries/index.md
theme:
  name: 'material'
